name: Build APK

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        default: 'TemplateApp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    # Step 3: Set up Node.js version 16
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 4: Set up Android SDK with API level 31 and build tools 31.0.0
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31  # Set the required API level (31 for Android 12)
        build-tools: 31.0.0  # Build tools version
        cmdline-tools-version: "latest"  # Ensure you're using the latest command-line tools

    # Step 5: Ensure gradlew is executable
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    # Step 6: Install npm dependencies
    - name: Install npm dependencies
      run: npm install

    # Step 7: Install Android dependencies and build the APK
    - name: Install dependencies and build APK
      run: cd android && ./gradlew assembleRelease

    # Step 8: Create a new GitHub Release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.appName }}-${{ github.run_id }}
        release_name: ${{ github.event.inputs.appName }} Release
        draft: false
        prerelease: false

    # Step 9: Upload the generated APK to the GitHub Release
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android/app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
