name: Build APK

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        default: 'TemplateApp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: 31.0.0
        cmdline-tools-version: "latest"

    # Clean and reinstall npm dependencies
    - name: Clean npm cache and reinstall dependencies
      run: |
        npm cache clean --force
        npm install

    # Ensure gradlew is executable
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    # Clean Android build
    - name: Clean Android build
      run: cd android && ./gradlew clean

    # Run autolinking manually
    - name: Run React Native autolinking
      run: npx react-native autolink

    # List contents of autolinking directory
    - name: List autolinking directory contents
      run: ls -la android/build/generated/autolinking

    # Build APK
    - name: Install dependencies and build APK
      run: cd android && ./gradlew assembleRelease

    # Create GitHub Release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.appName }}-${{ github.run_id }}
        release_name: ${{ github.event.inputs.appName }} Release
        draft: false
        prerelease: false

    # Upload APK to Release
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android/app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
